### ISSUE TITLE
jeff apache-2.0 will get "IndexError: tuple index out of range" exception

### ISSUE THREAD

**Issue by benjamin99** [oskarcieslik/Jeff#4]
The full traceback:
`Traceback (most recent call last):
  File "/Users/admin/Projects/wantoto/medical-solutions/venv/bin/jeff", line 9, in <module>
    load_entry_point('jeff==0.3.0', 'console_scripts', 'jeff')()
  File "/Users/admin/Projects/wantoto/medical-solutions/venv/lib/python3.4/site-packages/jeff/jeff.py", line 74, in main
    print(_get_filled_license(arguments["LICENSE_NAME"], arguments))
  File "/Users/admin/Projects/wantoto/medical-solutions/venv/lib/python3.4/site-packages/jeff/jeff.py", line 64, in _get_filled_license
    return _fill_license(license_template, arguments)
  File "/Users/admin/Projects/wantoto/medical-solutions/venv/lib/python3.4/site-packages/jeff/jeff.py", line 48, in _fill_license
    return license_template.format(**credentials)
IndexError: tuple index out of range
`

**Comment by rpunkfu** [comment]
Hi @benjamin99, good catch, fixed! :)
